function elapsedTime = readComputationalTimeOfBoard(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/mebner/UCL/UCL/Courses/Research Computing with
%    C++/courseworks/02_Conways Game of
%    Life/test/data/GameHistoryA_ComputationalTime.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/21 17:01:59

%% Initialize variables.
dir = 'GameHistories/';

delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%[^\n\r]';

%% Open the text file.
fileID = fopen([dir filename],'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
elapsedTime = dataArray{:, 1};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end